### ISSUE TITLE
Possible to use regex/glob pattern to ignore multiple packages?

### ISSUE THREAD

**Issue by afuetterer** [FHPythonUtils/LicenseCheck#108]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar questions in the project's issue tracker to avoid duplicates.
- [x] I have searched existing issues to see if this question has been asked before.

## Your Question

I use licensecheck as a pre-commit hook.

```yaml
- repo: https://github.com/FHPythonUtils/LicenseCheck/
  rev: ce61579e4b9bb83d0697f78997a400d7a2554a4f  # frozen: 2024.3
  hooks:
  - id: licensecheck
```
with these settings

```toml
[tool.licensecheck]
using = "PEP631"
```

My dependencies include

```toml
dependencies = [
  ...
  "spacy[cuda12x]>=3.8"
  ...
]
```

In my output I get the following:

```console
│ ✖          │ nvidia-cublas-cu12       │ OTHER/PROPRIETARY LICENSE            │
│ ✖          │ nvidia-cuda-cupti-cu12   │ OTHER/PROPRIETARY LICENSE            │
│ ✖          │ nvidia-cuda-nvrtc-cu12   │ OTHER/PROPRIETARY LICENSE            │
│ ✖          │ nvidia-cuda-runtime-cu12 │ OTHER/PROPRIETARY LICENSE            │
│ ✖          │ nvidia-cudnn-cu12        │ OTHER/PROPRIETARY LICENSE            │
│ ✖          │ nvidia-cufft-cu12        │ OTHER/PROPRIETARY LICENSE            │
│ ✖          │ nvidia-curand-cu12       │ OTHER/PROPRIETARY LICENSE            │
│ ✖          │ nvidia-cusolver-cu12     │ OTHER/PROPRIETARY LICENSE            │
│ ✖          │ nvidia-cusparse-cu12     │ OTHER/PROPRIETARY LICENSE            │
│ ✖          │ nvidia-cusparselt-cu12   │ NVIDIA PROPRIETARY SOFTWARE          │
│ ✖          │ nvidia-nccl-cu12         │ OTHER/PROPRIETARY LICENSE            │
│ ✖          │ nvidia-nvjitlink-cu12    │ OTHER/PROPRIETARY LICENSE            │
│ ✖          │ nvidia-nvtx-cu12         │ OTHER/PROPRIETARY LICENSE            │
```

Is there a way to ignore packages with something like `nvidia-*`?
