### ISSUE TITLE
Bug: Not able to ignore packages using pyproject.toml configuration

### ISSUE THREAD

**Issue by SamuelCabralCruz** [FHPythonUtils/LicenseCheck#53]
Hi, I have the following configuration in my project for licensecheck tool, but even if I try to ignore pylint, the licensecheck will still mark it as non compatible.

```toml
[tool.licensecheck]
format = "simple"
ignore_packages = ["pylint", "hypothesis"]
zero = true
```

I would expect the licensecheck to force compatibility for those two packages and return a 0 value.

Otherwise, I truly appreciate your tool 💪 .
