### ISSUE TITLE
Feature: Different Configuration Environments

### ISSUE THREAD

**Issue by Triavanicus** [FHPythonUtils/LicenseCheck#99]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar feature requests in the project's issue tracker
  to avoid duplicates.
- [x] I have searched existing issues to see if this feature has been discussed
  before.

## Feature Details

Create a way to manage different rules for different environments, as some licenses have different requirements on whether you are using them, or distributing them, and someone or a company may want a way to manage which licenses are used during which development phase.

### Describe the solution you'd like

Have the ability to create keys to manage different environments within a configuration file, similar to how tox may configure it: `[tool.licensecheck]` vs `[tool.licensecheck.env_name]`.

Example configuration:
```toml
[tool.licensecheck]
additional_envs = ["dev"]
using = "PEP631"
fail_licenses = ["mpl", "lgpl", "gpl"]

[tool.licensecheck.dev]
using = "PEP631:dev"
# overrides the base on only the changed attributes, and would still fail "gpl"
ignore_licenses = ["mpl", "lgpl"]
ignore_packages = ["textual-serve"]
```

Running it without any arguments would result in adding an additional column that states under which of the environments `licensecheck` fails, with it being empty for the base environment (and the column omitted if it is the only environment) and the name of the other environments.

### Describe alternatives you've considered

Currently, the workaround is to run `licensecheck` multiple times with different arguments to get all of the validation (which is also acceptable, but it would be nicer to manage it all in a config file under its configuration).

### Epilog
Thank you for taking time out of your day to review this request, and thank you for the product that you have already produced.
